spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projeto_angular_spring?useSSL=false
    username: root
    password: 123456789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true